#!/bin/sh

# tmp, .gitignored
rm -rf ./dev/tmp && mkdir -p ./dev/tmp/{logs,mnesia}

# Procfile
PROC=./dev/tmp/Procfile

# Init
:> $PROC

# Start of the available port range
PORT=5672

# Delay between Proctype starts
DELAY=1

for file in ./dev/*.config
do
    # Get the name from the config file, minus the ext
    path=$(basename "${file}")
    name="${path%.*}"

    # Specify the env variables
    env="RABBITMQ_NODENAME=${name}
         RABBITMQ_NODE_PORT=${PORT}
         RABBITMQ_CONFIG_FILE=../${name}
         RABBITMQ_ENABLED_PLUGINS_FILE=../enabled_plugins
         RABBITMQ_MNESIA_BASE=./mnesia
         RABBITMQ_LOG_BASE=./logs"

    # Command to run from the wrapper
    cmd=`echo "sleep ${DELAY}; ${env} rabbitmq-server" | tr -s " " | tr "\n" " "`

    # Wrapper script for Procfile command
    wrapper=./dev/tmp/$name

    # Add the command to the wrapper, wiping existing contents
    echo $cmd > $wrapper

    # Make wrapper executable
    chmod +x $wrapper

    # Add a line to the Procfile
    echo "${name}: ./${name}" >> $PROC

    # Increment the port range
    PORT=$[$PORT + 1]

    # Increment the delay
    DELAY=$[$DELAY + 2]
done

foreman start -f $PROC
